name: Build ML_CI_CD Workflow

runs:
  using: composite

  steps:

  - name: Install Conda
    uses: conda-incubator/setup-miniconda@v2
    with:
      auto-update-conda: true
      activate-environment: base
      use-only-tar-bz2: true  # Prevents compatibility issues

  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-conda-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    if: steps.cached-conda-dependencies.outputs.cache-hit != 'true'
    run: make install
    shell: bash