name: Build ML_CI_CD Workflow

runs:
  using: composite

  steps:
  - name: Install Conda
    uses: s-weigand/setup-conda@v1
    with:
      activate-conda: false  # Prevents automatic activation of `base`

  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-conda-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    if: steps.cached-conda-dependencies.outputs.cache-hit != 'true'
    run: |
      source $CONDA/bin/activate base  # Activate base environment correctly
      conda update -n base --all -y  # Update base instead of creating it
      conda info --envs  # Verify Conda environments
      make install
    shell: bash
