name: Build ML_CI_CD Workflow

runs:
  using: composite

  steps:
  - name:  Install Poetry
    uses: snok/install-poetry@v1
    with:
      virtualenv-in-project: true

  - name: Load cached venv
    uses: actions/cache@v4
    id: cached-poetry-dependencies
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    run: make install
    shell: bash